version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: patronative_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p4tron4tiv3
      POSTGRES_DB: patronative
  app:
    container_name: patronative_app
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - "postgres"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patronative_db:5432/patronative
volumes:
  pgdata: