version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: patronative_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p4tron4tiv3
      POSTGRES_DB: patronative
volumes:
  pgdata: