version: '3.9'
services:
  frontend:
    container_name: frontend_app
    build:
      context: ../patronage21-java-frontend/

  backend:
    container_name: backend_app
    build:
      context: .
    depends_on:
      - "postgres"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patronative_db:5432/patronative

  postgres:
    image: postgres:latest
    container_name: patronative_db
    ports:
      - 5101:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p4tron4tiv3
      POSTGRES_DB: patronative

  revproxy:
    image: nginx:latest
    container_name: revproxy
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./src/main/resources/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  pgdata:
