spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patronative
    username: admin
    password: p4tron4tiv3
    driverClassName: org.postgresql.Driver
    initialize: true
    initialization-mode: always
    schema: classpath:/db.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
validators:
  search:
    user:
      data:
        length:
          min: 2