spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patronative
    username: admin
    password: p4tron4tiv3
    driverClassName: org.postgresql.Driver
  flyway:
    schemas: patronative
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
validators:
  search:
    data:
      length:
        min: 2
  user:
    first-name:
      length:
        min: 2
        max: 30
    last-name:
      length:
        min: 2
        max: 30
    login:
      length:
        min: 2
        max: 15
    email-username:
      length:
        min: 3
        max: 30
    phone-number:
      length: 9
    github-username:
      length:
        min: 4
        max: 39
    projects:
      maximum-participation: 5